### POST request
POST http://localhost:8080/api/profiles
Content-Type: application/json

{
  "name": "Alice",
  "age": 18,
  "bio": "Loves hiking"
}


### DELETE request
DELETE http://localhost:8080/api/profiles/1

### GET request
GET http://localhost:8080/api/profiles/2



