### POST requests
POST http://localhost:8080/api/profiles
Content-Type: application/json

{
  "name": "Alice",
  "age": 18,
  "bio": "Loves hiking"
}

### GET requests
GET http://localhost:8080/api/profiles/1


### UPDATE requests
PUT http://localhost:8080/api/profiles/1
Content-Type: application/json

{
  "name": "dfsg",
  "age": 19,
  "bio": "Loafdafves hiking"
}


### DELETE requests
DELETE http://localhost:8080/api/profiles/1




